# .pre-commit-config.yaml

repos:
  - repo: local
    hooks:
      - id: format-tf
        name: Check and fix format of Terraform files
        entry: python3 scripts/format_tf.py
        language: system
        always_run: true
        pass_filenames: false
      - id: generate-docs
        name: Generate Terraform Module Documentation
        entry: python3 scripts/generate_tf_docs.py
        language: system
        always_run: true
        pass_filenames: false